import Link from "next/link";
import { capabilities, frameworks, industries, outcomes, solutions } from "@/lib/content";

export default function Home() {
  return <main>
    <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="live-dot" /> INFORMATION TECHNOLOGY & CYBERSECURITY</p><h1>Secure Technology.<br /><em>Smarter Transformation.</em><br />Resilient Business.</h1><p className="hero-intro">OYOON ALTAQNYA helps organizations design, implement, secure, and optimize modern technology environments across infrastructure, cloud, applications, data, digital transformation, and cybersecurity.</p><div className="hero-actions"><Link className="button button-primary" href="/contact">Talk to an expert <b>↗</b></Link><Link className="button button-quiet" href="#capabilities">Explore capabilities <b>↓</b></Link></div><div className="lifecycle"><span>ASSESS</span><i>→</i><span>ADVISE</span><i>→</i><span>ARCHITECT</span><i>→</i><span>IMPLEMENT</span><i>→</i><span>OPTIMIZE</span></div></div><div className="architecture-visual" aria-label="Secure digital architecture visualization"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="visual-core"><small>OAT</small><strong>↗</strong></div><span className="visual-node node-one">IDENTITY<br />GRAPH</span><span className="visual-node node-two">CLOUD<br />FABRIC</span><span className="visual-node node-three">RESILIENT<br />DATA</span><span className="visual-meta">ARCHITECTURE / 01<br />SECURITY BY DESIGN</span></div></section>
    <section className="promise"><span>Consult.</span><span>Design.</span><span>Implement.</span><span>Secure.</span><span>Optimize.</span></section>
    <section className="section about-section"><div className="section-label">01 / THE COMPANY</div><div className="two-column"><h2>Technology should make your business <em>braver.</em></h2><div><p>We bring technology and cybersecurity together so leaders can move with clarity. Our work spans the full lifecycle: assess, advise, architect, implement, secure, validate, and optimize.</p><Link className="inline-link" href="/about">Why OYOON ALTAQNYA <b>↗</b></Link></div></div></section>
    <section className="section dark-section" id="capabilities"><div className="section-heading"><div><div className="section-label">02 / WHAT WE DO</div><h2>One partner.<br /><em>Full capability.</em></h2></div><p>Enterprise-grade expertise across technology, security, and the systems that connect them.</p></div><div className="capability-grid">{capabilities.map((item, i) => <Link className={`capability-card card-${i % 4}`} href={item.href} key={item.number}><span className="card-number">{item.number}</span><h3>{item.title}</h3><p>{item.summary}</p><span className="card-arrow">↗</span></Link>)}</div></section>
    <section className="section outcomes-section"><div className="section-label">03 / BUSINESS OUTCOMES</div><h2>Make complexity <em>work for you.</em></h2><div className="outcomes-grid">{outcomes.map(([n, title, copy]) => <div key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></section>
    <section className="section solutions-section"><div className="section-heading"><div><div className="section-label">04 / CYBERSECURITY SOLUTIONS</div><h2>Security for the<br /><em>whole picture.</em></h2></div><Link className="inline-link" href="/solutions">View all solutions <b>↗</b></Link></div><div className="solution-grid">{solutions.map(([n, title, copy]) => <Link href="/solutions" key={n}><span>{n}</span><strong>{title}</strong><small>{copy}</small></Link>)}</div></section>
    <section className="section industry-section"><div className="section-label">05 / WHERE WE WORK</div><div className="two-column"><h2>Built for <em>critical environments.</em></h2><div className="industry-list">{industries.map((industry, index) => <Link href="/industries" key={industry}><span>0{index + 1}</span><strong>{industry}</strong><b>↗</b></Link>)}</div></div></section>
    <section className="section standards-section"><div><div className="section-label">06 / FRAMEWORKS</div><h2>Grounded in <em>good practice.</em></h2><p>Recommendations and delivery aligned with recognized industry frameworks. No implied certifications.</p></div><div className="framework-grid">{frameworks.map((framework) => <span key={framework}>{framework}</span>)}</div></section>
    <section className="final-cta"><div className="section-label">07 / START HERE</div><h2>Let&apos;s build a more <em>secure digital future.</em></h2><p>Whether you are modernizing infrastructure, strengthening cybersecurity, migrating to the cloud, or preparing for emerging threats, our experts can help.</p><div className="hero-actions"><Link className="button button-primary" href="/contact">Talk to an expert <b>↗</b></Link><Link className="button button-quiet" href="/rfp">Request a proposal <b>↗</b></Link></div></section>
  </main>;
}
